### ISSUE TITLE
Discrepancy in train lengths between left-moving and right-moving trains

### ISSUE THREAD

**Issue by ftpronk** [jo-m/trainbot#7]
There seems to be a mismatch in the estimated length between similar trains moving in different directions.

For instance, this left moving train is estimated as having a length of 205 m:
https://trains.jo-m.ch/#/trains/19476

Which is consistent with a similar left-moving train:
https://trains.jo-m.ch/#/trains/19494

However, right-moving trains at around the same time are considerably shorter, with this one estimated at 186 m:
https://trains.jo-m.ch/#/trains/19473

Or this one at 185 m:
https://trains.jo-m.ch/#/trains/19491

The same can be observed with other units. These left-going units are estimated at 104 m:
https://trains.jo-m.ch/#/trains/19410
https://trains.jo-m.ch/#/trains/19409

Whereas their right-moving friends are shorter, estimated at 98 and 97 m respectively:
https://trains.jo-m.ch/#/trains/19413
https://trains.jo-m.ch/#/trains/19414

What is also interesting, is that the left-moving units seem to be consistent in their estimated lengths at different speeds, which is no the case with similar right-moving trains.

**Comment by jo-m** [comment]
This program has no concept of 3d space - we are not doing any camera calibration or stereo vision.
A [single parameter](https://github.com/jo-m/trainbot/blob/master/cmd/trainbot/main.go#L44) is configured which tells trainbot how many meters equal a pixel. From this, all the length, speed, and accel measurements are derived.

Due to perspective, objects farther away from the camera will appear smaller in the camera image. This means that this parameter is only actually correct at a set of points (some sort of line or curved line) in the image which happen to have a certain distance from the camera.

In my case, I have set the parameter so that it is correct between the two parallel tracks in front of my camera.
That means all trains on the track closer to the camera will be estimated to be too long (and also too fast), and the opposite for the rear track.

In Switzerland, trains always drive on the left - so trains going to the left are always going to be closer to the camera than the ones going to the right.
